name: sabia_app
description: Rede social que reúne pensadores modernos

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  firebase_auth: ^4.1.2
  image_picker:
  firebase_storage:
  flutter_image_compress:
  path_provider:
  uuid:
  fluttertoast: ^8.0.8
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - config.env

